-- Seed gerado automaticamente a partir da planilha da JIW.
-- Fonte local: magia/clients/jiw/planilha_custos_servicos_ti.xlsx
-- Fonte remota: https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing
-- Total de servicos: 56

insert into tenant_service_catalog (
  tenant_id,
  external_source,
  external_id,
  category,
  name,
  description,
  billing_unit,
  price,
  estimated_hours,
  notes,
  metadata
)
select
  t.id,
  services.external_source,
  services.external_id,
  services.category,
  services.name,
  services.description,
  services.billing_unit,
  services.price,
  services.estimated_hours,
  services.notes,
  services.metadata
from tenants t
cross join (
  values
(
    'google_sheet_jiw_costs',
    '1',
    'Manutenção de Hardware',
    'Formatação e reinstalação do SO',
    'Backup, formatação e reinstalação do sistema operacional com drivers',
    'Por serviço',
    120,
    2,
    'Não inclui backup em nuvem',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '2',
    'Manutenção de Hardware',
    'Limpeza interna (notebook)',
    'Limpeza de poeira, cooler e troca de pasta térmica',
    'Por serviço',
    90,
    1,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '3',
    'Manutenção de Hardware',
    'Limpeza interna (desktop)',
    'Limpeza de poeira, cooler e troca de pasta térmica',
    'Por serviço',
    80,
    1,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '4',
    'Manutenção de Hardware',
    'Troca de HD para SSD',
    'Clonagem de disco e instalação de SSD',
    'Por serviço',
    100,
    1.5,
    'Peça não inclusa',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '5',
    'Manutenção de Hardware',
    'Upgrade de memória RAM',
    'Instalação e teste de novos módulos de memória',
    'Por serviço',
    60,
    0.5,
    'Peça não inclusa',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '6',
    'Manutenção de Hardware',
    'Troca de tela de notebook',
    'Substituição de tela LCD/LED danificada',
    'Por serviço',
    150,
    2,
    'Peça não inclusa',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '7',
    'Manutenção de Hardware',
    'Troca de teclado de notebook',
    'Substituição de teclado com defeito',
    'Por serviço',
    100,
    1,
    'Peça não inclusa',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '8',
    'Manutenção de Hardware',
    'Diagnóstico de placa-mãe',
    'Identificação de falhas em componentes da placa-mãe',
    'Por serviço',
    80,
    1,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '9',
    'Manutenção de Hardware',
    'Troca de bateria de notebook',
    'Substituição de bateria com baixa autonomia',
    'Por serviço',
    70,
    0.5,
    'Peça não inclusa',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '10',
    'Manutenção de Hardware',
    'Montagem de computador',
    'Montagem completa de PC gamer ou workstation',
    'Por serviço',
    200,
    3,
    'Peças não inclusas',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '11',
    'Manutenção de Software',
    'Remoção de vírus e malware',
    'Varredura completa e remoção de ameaças',
    'Por serviço',
    100,
    2,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '12',
    'Manutenção de Software',
    'Instalação do pacote Office',
    'Instalação e ativação do Microsoft Office',
    'Por serviço',
    70,
    1,
    'Licença não inclusa',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '13',
    'Manutenção de Software',
    'Instalação de antivírus corporativo',
    'Instalação e configuração de solução antivírus',
    'Por serviço',
    60,
    0.5,
    'Licença não inclusa',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '14',
    'Manutenção de Software',
    'Atualização de drivers e sistema',
    'Atualização geral do Windows e drivers de hardware',
    'Por serviço',
    50,
    1,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '15',
    'Manutenção de Software',
    'Otimização de desempenho',
    'Limpeza de arquivos temporários e otimização de boot',
    'Por serviço',
    90,
    1.5,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '16',
    'Manutenção de Software',
    'Configuração de e-mail corporativo',
    'Configuração de conta no Outlook/cliente de e-mail',
    'Por serviço',
    60,
    1,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '17',
    'Manutenção de Software',
    'Migração de sistema operacional',
    'Migração entre versões de Windows ou para Linux',
    'Por serviço',
    150,
    3,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '18',
    'Manutenção de Software',
    'Ativação e licenciamento de software',
    'Regularização de licenças de sistema e aplicativos',
    'Por serviço',
    50,
    0.5,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '19',
    'Redes e Infraestrutura',
    'Instalação de Wi-Fi residencial',
    'Configuração de roteador e otimização de sinal',
    'Por serviço',
    150,
    2,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '20',
    'Redes e Infraestrutura',
    'Instalação de Wi-Fi empresarial',
    'Projeto e instalação de rede sem fio corporativa',
    'Por serviço',
    400,
    5,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '21',
    'Redes e Infraestrutura',
    'Cabeamento estruturado',
    'Passagem e certificação de ponto de rede',
    'Por ponto',
    80,
    1,
    'Valor por ponto instalado',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '22',
    'Redes e Infraestrutura',
    'Configuração de roteador/switch',
    'Configuração de equipamentos de rede',
    'Por serviço',
    100,
    1.5,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '23',
    'Redes e Infraestrutura',
    'Instalação de servidor local',
    'Instalação e configuração de servidor de arquivos',
    'Por serviço',
    600,
    8,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '24',
    'Redes e Infraestrutura',
    'Configuração de VPN',
    'Configuração de acesso remoto seguro',
    'Por serviço',
    200,
    2,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '25',
    'Redes e Infraestrutura',
    'Monitoramento de rede',
    'Monitoramento contínuo de disponibilidade da rede',
    'Mensal',
    300,
    70,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '26',
    'Redes e Infraestrutura',
    'Instalação de câmeras (CFTV)',
    'Instalação e configuração de câmera de segurança',
    'Por ponto',
    180,
    2,
    'Câmera não inclusa',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '27',
    'Segurança da Informação',
    'Auditoria de segurança básica',
    'Avaliação de vulnerabilidades e boas práticas',
    'Por serviço',
    500,
    6,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '28',
    'Segurança da Informação',
    'Implementação de firewall',
    'Instalação e configuração de firewall de rede',
    'Por serviço',
    350,
    4,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '29',
    'Segurança da Informação',
    'Política de backup e segurança',
    'Consultoria para definição de políticas internas',
    'Por serviço',
    400,
    4,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '30',
    'Segurança da Informação',
    'Teste de vulnerabilidade (pentest básico)',
    'Análise de segurança em sistemas e rede',
    'Por serviço',
    800,
    10,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '31',
    'Segurança da Informação',
    'Configuração de autenticação em 2 fatores',
    'Implementação de 2FA em contas e sistemas',
    'Por serviço',
    80,
    1,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '32',
    'Desenvolvimento',
    'Site institucional',
    'Desenvolvimento de site institucional responsivo',
    'Por projeto',
    2500,
    40,
    'Valor pode variar conforme escopo',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '33',
    'Desenvolvimento',
    'E-commerce',
    'Loja virtual completa com integração de pagamento',
    'Por projeto',
    6000,
    80,
    'Valor pode variar conforme escopo',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '34',
    'Desenvolvimento',
    'Sistema web sob medida',
    'Desenvolvimento de sistema web personalizado',
    'Por hora',
    120,
    95,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '35',
    'Desenvolvimento',
    'Manutenção mensal de sistema/site',
    'Atualizações, correções e pequenas melhorias',
    'Mensal',
    300,
    70,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '36',
    'Desenvolvimento',
    'Aplicativo mobile básico',
    'Desenvolvimento de app Android/iOS (MVP)',
    'Por projeto',
    8000,
    120,
    'Valor pode variar conforme escopo',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '37',
    'Desenvolvimento',
    'Landing page',
    'Criação de página de captura otimizada',
    'Por projeto',
    800,
    10,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '38',
    'Desenvolvimento',
    'Integração de API de pagamento',
    'Integração com gateway de pagamento',
    'Por serviço',
    500,
    6,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '39',
    'Suporte Técnico',
    'Suporte remoto',
    'Atendimento técnico via acesso remoto',
    'Por hora',
    70,
    1,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '40',
    'Suporte Técnico',
    'Suporte presencial',
    'Atendimento técnico no local do cliente',
    'Por hora',
    100,
    1,
    'Taxa de deslocamento à parte',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '41',
    'Suporte Técnico',
    'Contrato mensal (até 5 máquinas)',
    'Suporte técnico ilimitado para até 5 equipamentos',
    'Mensal',
    450,
    70,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '42',
    'Suporte Técnico',
    'Contrato mensal (até 10 máquinas)',
    'Suporte técnico ilimitado para até 10 equipamentos',
    'Mensal',
    800,
    70,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '43',
    'Suporte Técnico',
    'Visita técnica emergencial',
    'Atendimento fora do horário comercial',
    'Por visita',
    200,
    2,
    'Sujeito a disponibilidade',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '44',
    'Backup e Recuperação',
    'Configuração de backup em nuvem',
    'Implantação de rotina automática de backup online',
    'Por serviço',
    150,
    2,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '45',
    'Backup e Recuperação',
    'Recuperação de dados',
    'Recuperação de dados em HD/SSD danificado',
    'Por serviço',
    300,
    4,
    'Sem garantia de sucesso total',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '46',
    'Backup e Recuperação',
    'Backup local automatizado',
    'Configuração de rotina de backup em HD externo/NAS',
    'Por serviço',
    120,
    1.5,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '47',
    'Backup e Recuperação',
    'Recuperação de arquivos apagados',
    'Recuperação de arquivos excluídos acidentalmente',
    'Por serviço',
    180,
    2,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '48',
    'Consultoria em TI',
    'Consultoria em infraestrutura',
    'Análise e recomendação de melhorias de TI',
    'Por hora',
    180,
    1,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '49',
    'Consultoria em TI',
    'Diagnóstico do parque de máquinas',
    'Levantamento completo de hardware e software',
    'Por serviço',
    400,
    6,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '50',
    'Consultoria em TI',
    'Plano de TI anual',
    'Elaboração de planejamento estratégico de TI',
    'Por projeto',
    1200,
    20,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '51',
    'Cloud / Nuvem',
    'Migração para nuvem',
    'Migração de servidor local para ambiente cloud',
    'Por serviço',
    900,
    12,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '52',
    'Cloud / Nuvem',
    'Configuração de e-mail em nuvem',
    'Configuração de Google Workspace ou Microsoft 365',
    'Por serviço',
    250,
    3,
    'Licenças não inclusas',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '53',
    'Cloud / Nuvem',
    'Gestão mensal de ambiente cloud',
    'Administração e monitoramento de infraestrutura cloud',
    'Mensal',
    500,
    70,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '54',
    'Impressoras e Periféricos',
    'Manutenção de impressora',
    'Limpeza de cabeça de impressão e ajustes gerais',
    'Por serviço',
    90,
    1.5,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '55',
    'Impressoras e Periféricos',
    'Instalação de impressora em rede',
    'Configuração de impressora compartilhada em rede',
    'Por serviço',
    70,
    1,
    null,
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  ),
(
    'google_sheet_jiw_costs',
    '56',
    'Impressoras e Periféricos',
    'Recarga de cartucho/toner',
    'Instalação de cartucho ou toner recarregado',
    'Por serviço',
    40,
    0.3,
    'Insumo não incluso',
    jsonb_build_object('source_url', 'https://docs.google.com/spreadsheets/d/1zRCmrFVhX8es_XNuvxbvMyeLuvFnbjhL-1WRsu5UoPc/edit?usp=sharing', 'local_file', 'magia/clients/jiw/planilha_custos_servicos_ti.xlsx')
  )
) as services (
  external_source,
  external_id,
  category,
  name,
  description,
  billing_unit,
  price,
  estimated_hours,
  notes,
  metadata
)
where t.slug = 'jiw'
on conflict (tenant_id, external_source, external_id) do update
set category = excluded.category,
    name = excluded.name,
    description = excluded.description,
    billing_unit = excluded.billing_unit,
    price = excluded.price,
    estimated_hours = excluded.estimated_hours,
    notes = excluded.notes,
    metadata = excluded.metadata,
    active = true,
    updated_at = now();

select
  'jiw_service_catalog_seed_ok' as status,
  count(*) as service_count
from tenant_service_catalog c
join tenants t on t.id = c.tenant_id
where t.slug = 'jiw'
  and c.external_source = 'google_sheet_jiw_costs';
