const fs = require('node:fs');
const path = require('node:path');
const ts = require('../app/node_modules/typescript');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const baseline = JSON.parse(read('n8n/workflows/magia_telegram_multitenant_v4_8_0_payment_signal.json'));
const source = baseline.nodes.find(node => node.parameters.jsCode).parameters.jsCode;
const boundary = source.indexOf('if (!tenantSlug) return');
if (boundary < 0) throw Error('Legacy core boundary missing');
function functions(code) {
  const ast = ts.createSourceFile('core.js', code, ts.ScriptTarget.Latest, true, ts.ScriptKind.JS);
  return new Map(ast.statements.filter(ts.isFunctionDeclaration).map(node => [node.name.text, node.getText(ast)]));
}
const extracted = functions(source.slice(0, boundary));
const overrides = functions(read('n8n/code/whatsapp_core_overrides.js'));
for (const [name, code] of overrides) extracted.set(name, code);
for (const [name, code] of functions(read('n8n/code/whatsapp_grounded_reply.js'))) extracted.set(name, code);
for (const [name, code] of functions(read('n8n/code/whatsapp_scheduling.js'))) extracted.set(name, code);
for (const [name, code] of functions(read('n8n/code/whatsapp_session.js'))) extracted.set(name, code);
const dateRule = '- Use essas datas como referencia oficial para termos relativos.';
if (!extracted.get('callGemini').includes(dateRule)) throw Error('Review legacy date instructions');
extracted.set('callGemini', extracted.get('callGemini').replace(dateRule,
  dateRule + '\n- Hoje e amanha ja sao datas especificas: converta para a data ISO acima, sem pedir a data novamente.\n- As mensagens da ultima entrada foram agrupadas: interprete todas como um pedido unico e responda uma unica vez.\n- Se nome, servico, dia e hora ja constarem na entrada ou no historico, execute a tag de criacao, sem repetir perguntas.'));
extracted.set('parseAppointmentCreationTag', extracted.get('parseAppointmentCreationTag')
  .replace("const source = String(text || '');", "const source = String(text || '').replace(/\\[A[C\\u00c7][A\\u00c3]O\\s*:/gi, '[ACAO:');"));
// Mechanical adapter, not a second copy of the clinic's business rules.
let library = [...extracted.values()].join('\n\n')
  .replaceAll('channel_type=eq.telegram', 'channel_type=eq.whatsapp')
  .replaceAll("channel_type: 'telegram'", "channel_type: 'whatsapp'")
  .replaceAll('telegram_chat_id:', 'whatsapp_chat_id:')
  .replaceAll('telegram_message_id:', 'whatsapp_message_id:');
const personalityStart = library.indexOf('- PERSONALIDADE OBRIGATÓRIA');
const personalityEnd = library.indexOf('- IMPORTANTE: animação', personalityStart);
if (personalityStart < 0 || personalityEnd < 0) throw Error('Legacy personality block changed; review before building');
library = library.slice(0, personalityStart)
  + '${settings.conversation_style_instructions || settings.tone || ""}\n'
  + library.slice(personalityEnd);
const code = '// Generated by scripts/build_whatsapp_core.cjs. Edit adapters/runtime, not this file.\n'
  + read('n8n/code/whatsapp_core_header.js') + '\n' + library + '\n' + read('n8n/code/whatsapp_core_runtime.js');
new (Object.getPrototypeOf(async function(){}).constructor)('$json', '$env', '$vars', '$getWorkflowStaticData', code);
fs.writeFileSync(path.join(root, 'n8n/code/whatsapp_conversation_core.generated.js'), code);
console.log('Built WhatsApp business core from Telegram V4.8.0 with scoped transport/runtime overrides.');
