const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const dir = path.join(root, 'clients/clinica_nubia_oficial');
const prompt = fs.readFileSync(path.join(dir, 'prompt_canonico_v2.txt'), 'utf8').trim();
const facts = JSON.parse(fs.readFileSync(path.join(dir, 'business_facts_v2.json'), 'utf8'));
const value = JSON.stringify({ grounding_mode: 'canonical_v2', prompt_revision: 'nubia-2026-09-29-angra-sessoes-v5',
  ai_model: 'gemini-2.5-flash', system_prompt: prompt, business_facts: facts }, null, 2);
if (value.includes('$canonical$')) throw Error('SQL delimiter collision');
const sql = `-- Generated by scripts/build_nubia_grounding_sql.cjs; edit the source prompt/facts.
-- JA aplicado por API em 2026-09-25. Nao e necessario executar novamente.
-- Requer workflow com canonical_v2 publicado; preserva outros tenants e payment.
begin;
do $$
declare affected integer;
begin
  update public.tenant_settings s
  set settings = (s.settings - 'conversation_style_instructions') || $canonical$${value}$canonical$::jsonb,
      updated_at = now()
  from public.tenants t
  where t.id = s.tenant_id and t.slug = 'clinica_nubia_oficial'
    and s.settings->>'whatsapp_processing_mode' = 'conversation_core_v1';
  get diagnostics affected = row_count;
  if affected <> 1 then raise exception 'Tenant/core oficial nao encontrado ou duplicado'; end if;
end $$;
commit;
`;
fs.writeFileSync(path.join(dir, '04_fonte_unica_whatsapp.sql'), sql);
console.log('Generated official tenant grounding SQL from canonical source files.');
