-- Base de conhecimento aprovada para RAG por tenant.
-- A tabela nao recebe conversas automaticamente: a ingestao deve passar por
-- um fluxo de revisao/curadoria antes de gerar o embedding.

create extension if not exists vector with schema extensions;

create table if not exists public.ai_knowledge_documents (
  id bigint generated by default as identity primary key,
  -- O n8n Vector Store grava content/metadata/embedding. O trigger abaixo
  -- deriva o tenant_slug do metadata para manter a coluna canonica sempre
  -- preenchida sem expor uma coluna extra no no visual.
  tenant_slug text not null default 'unknown',
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding extensions.vector(1536),
  source_type text not null default 'approved_content',
  source_ref uuid,
  approved boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ai_knowledge_documents
  alter column tenant_slug set default 'unknown';

create index if not exists ai_knowledge_documents_tenant_idx
  on public.ai_knowledge_documents (tenant_slug, approved);

create index if not exists ai_knowledge_documents_embedding_idx
  on public.ai_knowledge_documents
  using hnsw (embedding extensions.vector_cosine_ops);

create or replace function public.set_ai_knowledge_tenant_slug()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.metadata ? 'tenant_slug'
     and nullif(trim(new.metadata->>'tenant_slug'), '') is not null then
    new.tenant_slug := trim(new.metadata->>'tenant_slug');
  end if;
  return new;
end;
$$;

drop trigger if exists ai_knowledge_tenant_slug on public.ai_knowledge_documents;
create trigger ai_knowledge_tenant_slug
before insert or update of metadata on public.ai_knowledge_documents
for each row execute function public.set_ai_knowledge_tenant_slug();

create or replace function public.match_ai_knowledge(
  query_embedding extensions.vector(1536),
  match_count integer default 5,
  filter jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity double precision
)
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
  return query
  select
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) as similarity
  from public.ai_knowledge_documents d
  where d.approved = true
    and d.embedding is not null
    -- O tenant_slug e validado na coluna canonica. O metadata e usado apenas
    -- para filtros adicionais enviados pelo no do n8n.
    and (
      filter->>'tenant_slug' is null
      or d.tenant_slug = filter->>'tenant_slug'
    )
    and d.metadata @> (coalesce(filter, '{}'::jsonb) - 'tenant_slug')
  order by d.embedding <=> query_embedding
  limit greatest(match_count, 1);
end;
$$;

alter table public.ai_knowledge_documents enable row level security;

-- O n8n acessa esta tabela com a credencial service_role. Nao liberar leitura
-- direta para authenticated antes de existir uma policy por tenant_members.
revoke all on table public.ai_knowledge_documents from anon, authenticated;
revoke all on function public.match_ai_knowledge(extensions.vector(1536), integer, jsonb) from public;
grant execute on function public.match_ai_knowledge(extensions.vector(1536), integer, jsonb) to service_role;

comment on table public.ai_knowledge_documents is
  'Documentos aprovados e isolados por tenant usados pelo RAG do assistente JIW';
